linters:
    enable-all: true
    disable:
        - exhaustivestruct
        - gochecknoinits
        - gochecknoglobals
        - gci
        - varnamelen
        - wrapcheck
        - durationcheck
        - ireturn
