version: '2.0'

services:
    postgres_db:
        image: postgres:14-alpine3.15
        container_name: postgres_db
        restart: always
        environment:
            - DATABASE_HOST=localhost
        env_file:
            - .env
        networks:
            - default
        ports:
          - 5810:5432

    app_server:
        build: .
        container_name: app_server
        ports:
            - 5800:5800
        user: root
        depends_on:
            - postgres_db
        restart: always
        environment:
            HOST: postgres_db
        env_file:
            - .env
        networks:
            - default
networks:
  default:
    driver: bridge
