version: '2.0'

services:
    postgres_db:
        image: postgres:14-alpine3.15
        container_name: postgres_db
        restart: always
        environment:
            - DATABASE_HOST=localhost
        env_file:
            - .env
        networks:
            - default
        ports:
          - 5810:5432
        volumes:
            - ./build/database/data:/var/lib/postgresql/data:rw

    redis_cache:
        image: redis:7.0.0-alpine
        container_name: redis_cache
        restart: always
        networks:
            - default
        ports:
            - 5820:6379

    app_server:
        build: .
        container_name: app_server
        ports:
            - 5800:5800
        user: root
        depends_on:
            - postgres_db
            - redis_cache
        restart: always
        env_file:
            - .env
        networks:
            - default
networks:
  default:
    driver: bridge
