// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package sqlc

import (
	"database/sql"
	"time"
)

type Profile struct {
	ID             int32        `db:"id" json:"id"`
	LastConnection sql.NullTime `db:"last_connection" json:"lastConnection"`
	CreatedAt      time.Time    `db:"created_at" json:"createdAt"`
	UpdatedAt      time.Time    `db:"updated_at" json:"updatedAt"`
}

type User struct {
	ID        int32        `db:"id" json:"id"`
	Username  string       `db:"username" json:"username"`
	Firstname string       `db:"firstname" json:"firstname"`
	Lastname  string       `db:"lastname" json:"lastname"`
	Email     string       `db:"email" json:"email"`
	Password  string       `db:"password" json:"password"`
	Role      string       `db:"role" json:"role"`
	Birthday  sql.NullTime `db:"birthday" json:"birthday"`
	CreatedAt time.Time    `db:"created_at" json:"createdAt"`
	UpdatedAt time.Time    `db:"updated_at" json:"updatedAt"`
}
