// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: queries.sql

package provider

import (
	"context"

	"github.com/lib/pq"
)

const changePasswordByID = `-- name: ChangePasswordByID :exec
UPDATE users SET password = $1 WHERE id = $2
`

type ChangePasswordByIDParams struct {
	Password string `db:"password" json:"password"`
	ID       int32  `db:"id" json:"id"`
}

func (q *Queries) ChangePasswordByID(ctx context.Context, arg ChangePasswordByIDParams) error {
	_, err := q.db.ExecContext(ctx, changePasswordByID, arg.Password, arg.ID)
	return err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles(id) VALUES($1) RETURNING id, last_connection, created_at, updated_at
`

func (q *Queries) CreateProfile(ctx context.Context, id int32) (Profile, error) {
	row := q.db.QueryRowContext(ctx, createProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.LastConnection,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, firstname, lastname, email, password, roles) 
VALUES($1, $2, $3, $4, $5, $6) RETURNING id, username, firstname, lastname, email, password, roles, birthday, created_at, updated_at
`

type CreateUserParams struct {
	Username  string   `db:"username" json:"username"`
	Firstname string   `db:"firstname" json:"firstname"`
	Lastname  string   `db:"lastname" json:"lastname"`
	Email     string   `db:"email" json:"email"`
	Password  string   `db:"password" json:"password"`
	Roles     []string `db:"roles" json:"roles"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Firstname,
		arg.Lastname,
		arg.Email,
		arg.Password,
		pq.Array(arg.Roles),
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.Password,
		pq.Array(&i.Roles),
		&i.Birthday,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUserByID, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, firstname, lastname, email, password, roles, birthday, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.Password,
		pq.Array(&i.Roles),
		&i.Birthday,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsernameOrEmail = `-- name: GetUserByUsernameOrEmail :one
SELECT id, username, firstname, lastname, email, password, roles, birthday, created_at, updated_at FROM users WHERE username = $1 OR email = $2
`

type GetUserByUsernameOrEmailParams struct {
	Username string `db:"username" json:"username"`
	Email    string `db:"email" json:"email"`
}

func (q *Queries) GetUserByUsernameOrEmail(ctx context.Context, arg GetUserByUsernameOrEmailParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsernameOrEmail, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.Password,
		pq.Array(&i.Roles),
		&i.Birthday,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, username, firstname, lastname, email, password, roles, birthday, created_at, updated_at FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Firstname,
			&i.Lastname,
			&i.Email,
			&i.Password,
			pq.Array(&i.Roles),
			&i.Birthday,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userExists = `-- name: UserExists :one
SELECT exists(SELECT id, username, firstname, lastname, email, password, roles, birthday, created_at, updated_at FROM users WHERE id = $1)
`

func (q *Queries) UserExists(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userExistsByUsernameOrEmail = `-- name: UserExistsByUsernameOrEmail :one
SELECT exists(SELECT id, username, firstname, lastname, email, password, roles, birthday, created_at, updated_at FROM users WHERE username=$1 OR email=$2)
`

type UserExistsByUsernameOrEmailParams struct {
	Username string `db:"username" json:"username"`
	Email    string `db:"email" json:"email"`
}

func (q *Queries) UserExistsByUsernameOrEmail(ctx context.Context, arg UserExistsByUsernameOrEmailParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExistsByUsernameOrEmail, arg.Username, arg.Email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
