name: Go

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v3.2.0
              with:
                  go-version: 1.18.2
                  check-latest: true
                  go-version-file: ./go.mod
                  cache-dependency-path: ./go.sum
                  # cache: enable

            - name: Build
              run: go build -v ./...

            - name: Tests
              run: go test -v ./...

            # - name: auto-gofmt
            #   uses: iamnotaturtle/auto-gofmt@v2.0.0
            #   with:
            #       commit_message: Go code formatted
