name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: auto-gofmt
      # You may pin to the exact commit or the version.
      # uses: iamnotaturtle/auto-gofmt@5ccb127d147a6f2ea59bcb004be858eb89dc7fbd
      uses: iamnotaturtle/auto-gofmt@v2.0.0
      with:
        # Commit message, will be ignored if used with same_commit
        commit_message: Formatted
